### ISSUE TITLE
Question about the visulaization tool used in the demo video

### ISSUE THREAD

**Issue by edward9503** [fdevinc/ungar#5]
Hi @fdevinc ,

first of all, thank you for sharing your impressive work. That really helps to reduce a lot of workload. 

I am curious about the visualization of the robot in demo video like https://www.youtube.com/watch?v=iKQ6felf45k. What kind of visualizer you are using? And I couldn't find it in the source code. 

Many thanks.

**Comment by fdevinc** [comment]
Hello @edward9503, I appreciate your kind words and reaching out! Those demos utilize an in-house graphics library based on [OpenGL](https://www.opengl.org/) and [GLFW](https://www.glfw.org/) developed by [CRL](https://crl.ethz.ch/), which I am unable to share. However, I am excited about the possibility of integrating visualization features with Ungar in the future. Unfortunately, if this ever happens, it will take at least a couple of years to materialize. Thank you for your understanding!
